[uwsgi]
chdir = /usr/local/searxng/searxng-src
module = searx.webapp
plugins = python3
master = true
processes = 2
threads = 2
socket = 127.0.0.1:8080
chmod-socket = 666
vacuum = true
die-on-term = true
lazy-apps = true
env = SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
